### ISSUE TITLE
Inconsistency date separater between *.rb and *.el files

### ISSUE THREAD

**Issue by ikazuhiro** [yoshinari-nomura/mhc#31]
Emacs's MHC-Draft mode accepts `,`as date separater but MHC script does not.  For example, 
```
X-SC-Day: 20150601, 20150602
```
I can `mhc-draft-finish` with such header, but MHC script accepts only ` `, outputs error message and stops.  `M-x mhc` can't run anymore.  Which should be correct?

**Comment by yoshinari-nomura** [comment]
Sorry for the lack of documents.
Comma-separated style is not supported officially, please use white-space for the delimiter.

**Comment by ikazuhiro** [comment]
Thank you for the comment.  Is there any reason `mhc-logic/space-regexp` contains `,` and `|`?

**Comment by yoshinari-nomura** [comment]
I almost forgot the reason... but, basically I do not prefer to introduce such kind of ambiguity to
the core syntax.

I should have removed these ambiguity at the early stage of our development.

**Comment by ikazuhiro** [comment]
I see, thank you for your comment.
