### ISSUE TITLE
incorrect mhc-version in Emacs

### ISSUE THREAD

**Issue by tats** [yoshinari-nomura/mhc#32]
In Emacs, mhc-version is still "mhc 1.0.0".  Please sync the version when releasing.

**Comment by yoshinari-nomura** [comment]
Thanks.
I've pushed two commits 176d3ed and  e5bf2c2.
I believe I can keep the consistency of version numbers for future releases by  e5bf2c2.

**Comment by tats** [comment]
> I've pushed two commits 176d3ed and e5bf2c2.

Closing, thank you.
