### ISSUE TITLE
mhc-file-sync is unusable in Emacs

### ISSUE THREAD

**Issue by tats** [yoshinari-nomura/mhc#33]
In Emacs, `C-c . S` (mhc-file-sync) is unusable, because the external command
mhc-sync is obsolete.  Please mention `mhc sync`, or unbind the key.

**Comment by yoshinari-nomura** [comment]
Yes, some of key binds are obsolete.
Since mhc-summary had become major-mode, I newly made a keymap for that.
I should have obsoleted the whole minor-mode keymap prefixed `C-c .`
I'm going to do that in the future release.

As a quick remedy, I pushed fc5024b.

**Comment by tats** [comment]
> As a quick remedy, I pushed fc5024b.

Thanks, closing.
