### ISSUE TITLE
Inconsistency between mhc-db-add-exception-rule and mhc-db-add-record-from-buffer

### ISSUE THREAD

**Issue by ikazuhiro** [yoshinari-nomura/mhc#47]
`mhc-db-add-exception-rule` function calls `mhc-db-add-record-from-buffer` with two argument, RECORD and BUFFER.  But `mhc-db-add-record-from-buffer` does not accept RECORD argument.

**Comment by ikazuhiro** [comment]
I confirmed the problem is fixed by your commit https://github.com/yoshinari-nomura/mhc/commit/63031a79b5ad759c6e4e2c30288dce1caa12f7e5 .
Thank you!

**Comment by yoshinari-nomura** [comment]
Thank you for your cooperation.
Sorry, I should have refer your report #47.
