### ISSUE TITLE
"mhc init" fails

### ISSUE THREAD

**Issue by kikirinrin** [yoshinari-nomura/mhc#51]
Hello, whould you help me with `mhc init` ?
It fails returning msg below.
```
$ mhc init ~/mhc                                                                                                                     341ms  Mon Aug  5 20:06:01 2019
Guessing current local timezone ...
          ok  guess timezone ... Asia/Tokyo
Making directries under /Users/ahayashi/mhc ...
      failed  uninitialized constant Mhc::Command::Init::FileUtils
Did you mean?  FileTest /Users/ahayashi/mhc/draft
      failed  uninitialized constant Mhc::Command::Init::FileUtils
Did you mean?  FileTest /Users/ahayashi/mhc/inbox
      failed  uninitialized constant Mhc::Command::Init::FileUtils
Did you mean?  FileTest /Users/ahayashi/mhc/presets
      failed  uninitialized constant Mhc::Command::Init::FileUtils
Did you mean?  FileTest /Users/ahayashi/mhc/spool
      failed  uninitialized constant Mhc::Command::Init::FileUtils
Did you mean?  FileTest /Users/ahayashi/mhc/trash
      failed  uninitialized constant Mhc::Command::Init::FileUtils
Did you mean?  FileTest /Users/ahayashi/mhc/status/cache
      failed  uninitialized constant Mhc::Command::Init::FileUtils
Did you mean?  FileTest /Users/ahayashi/mhc/status/log
      failed  uninitialized constant Mhc::Command::Init::FileUtils
Did you mean?  FileTest /Users/ahayashi/mhc/status/sync_channels
Copying config file(s) into ~/.config/mhc/config.yml ...
      failed  uninitialized constant Mhc::Command::Init::FileUtils
Did you mean?  FileTest /Users/ahayashi/.config/mhc
      failed  No such file or directory /Users/ahayashi/.config/mhc/config.yml
10 error(s) were occurred.
```
Would you tell me where I made a mistake?

**Comment by yoshinari-nomura** [comment]
Thanks for reporting.
Let me know your Ruby version?

And, if you can edit the file lib/mhc/command/init.rb,
please try to prepend this  line:
```Ruby
require "fileutils"
```
at the top of init.rb.

I guess recent Ruby needs explicit `require` to use FileUtils

**Comment by kikirinrin** [comment]
Thanks for quick reply.
> Let me know your Ruby version?
My ruby version is
`ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]`.

**Comment by kikirinrin** [comment]
> edit the file lib/mhc/command/init.rb

Excuse me, how should I find init.rb on my computer (I just `gem install`ed mhc) ?

Should I
- `clone` this repo
- `cd lib/mhc/command/init.rb`
- run some command like `make` ?

Sorry for my question because I'm completely novice on ruby.

**Comment by ykasap** [comment]
@kikirinrin I guess you are using `/usr/bin/ruby` bundled with macOS Mojave because it says "universal.x86_64-darwin18".

`/usr/bin/gem` installs files under `/Library/Ruby/Gems`.  I found `lib/mhc/command/init.rb` in
`/Library/Ruby/Gems/2.3.0/gems/mhc-1.2.2/lib/mhc/command/init.rb`.

Insert `require "fileutils"` at the beginning of this file.  I confirmed that `mhc init ~/mhc` worked as expected after adding this line on macOS 10.13.6.

Another option is to install a more recent version of ruby using Homebrew or MacPorts and use them.

**Comment by yoshinari-nomura** [comment]
@ykasap thanks!

**Comment by yoshinari-nomura** [comment]
I've released mhc 1.2.3 to rubygems.org including the fix for this issue.

**Comment by kikirinrin** [comment]
It worked!!!
Thank you a lot!

**Comment by kikirinrin** [comment]
@ykasap 
I managed to find `lib/` under the path you told me.
Thank you very much!
